# 1. Import Libraries

In [2]:
import pandas as pd
import numpy as np

# 2. Homework

### 1. Check pandas ver.

In [3]:
pd.__version__

'2.2.3'

### 2. Check num of records

In [4]:
df = pd.read_csv("laptops.csv")

df

Laptop       Status   Brand  \
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

           Model                CPU  RAM  Storage Storage type       GPU  \
0     ExpertBook      Intel Core i5    8      512          SSD       NaN   
1             Go      Intel Celeron    8      256          SSD       NaN   
2     ExpertBook      Intel Core i3    8      256          SSD       NaN   
3         Katana      Intel Core i7   16     1000          SSD  RTX 3050   
4            15S      Intel Core i5   16      512          SSD       NaN   
...          ...                ...  ...      ...          ...       ...   
2155       Blade      Intel Core i7   16     1000          SSD  RTX 3060   
2156       Blade      Intel Core i7   16     1000          SSD  RTX 3070   
2157       Blade      Intel Core i7   32     1000          SSD  RTX 3080   
2158        Book  Intel Evo Core i7   16     1000          SSD       NaN   
2159        Book  Intel Evo Core i7   16      256          SSD       NaN   

      Screen Touch  Final Price  
0       15.6    No      1009.00  
1       15.6    No       299.00  
2       15.6    No       789.00  
3       15.6    No      1199.00  
4       15.6    No       669.01  
...      ...   ...          ...  
2155    17.3    No      2699.99  
2156    17.3    No      2899.99  
2157    17.3    No      3399.99  
2158    13.4   Yes      1899.99  
2159    13.4   Yes      1699.99  

[2160 rows x 12 columns]

### 3. num. of available laptop brands

In [5]:
df['Brand'].nunique()

27

### 4. Missing values

In [6]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

### 5. Using Describe to find max price

In [7]:
df[df['Brand']=='Dell'].describe()

RAM      Storage     Screen  Final Price
count  84.000000    84.000000  84.000000    84.000000
mean   11.380952   395.142857  14.686905  1153.839881
std     4.583640   175.543846   1.023669   671.795071
min     4.000000   128.000000  13.000000   379.000000
25%     8.000000   256.000000  14.000000   699.000000
50%     8.000000   256.000000  14.500000  1003.000000
75%    16.000000   512.000000  15.600000  1313.810000
max    32.000000  1000.000000  17.000000  3936.000000

### 6. Median Value of Screen

In [8]:
median = df['Screen'].median()
print(median)

modus = df['Screen'].mode()
print(modus)

# Fillna with modus
df['screen'] = df['Screen'].fillna(modus)

# Check Screen median
df['screen'].median()

15.6
0    15.6
Name: Screen, dtype: float64


15.6

### 7. Matrix multiplication: Sum of weight

In [10]:
innjoo_laptops = df[df['Brand'] == 'Innjoo']

innjoo_laptops

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  \
1478  Intel Celeron    8      256          SSD  NaN    15.6    No   
1479  Intel Celeron    8      512          SSD  NaN    15.6    No   
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No   
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No   
1482  Intel Celeron    6      128          SSD  NaN    14.1    No   
1483  Intel Celeron    6      128         eMMC  NaN    14.1    No   

      Final Price  screen  
1478       311.37    15.6  
1479       392.55    15.6  
1480       251.40    14.1  
1481       383.61    14.1  
1482       317.02    14.1  
1483       431.38    14.1

In [12]:
# Select only columns RAM, Storage, Screen
X = innjoo_laptops[['RAM', 'Storage', 'Screen']].values

X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [13]:
# Matrix-matrix multiplication between X.T and X (XTX)
XTX = X.T @ X

XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [14]:
# the inverse of XTX
XTX_inv = np.linalg.inv(XTX)

In [16]:
# create the array y
y = np.array([1100, 1300, 800, 900, 1000, 1100])

y

array([1100, 1300,  800,  900, 1000, 1100])

In [17]:
# Multiply inverse(XTX) with X.T, then multiply with y to get w
w = XTX_inv @ X.T @ y

# Sum of all elements of w
result_sum = np.sum(w)

result_sum

91.2998806299557